### ISSUE TITLE
Future of the nLab

### ISSUE THREAD

**Issue by ghost** [ncatlab/nlab#14]
Richard Williamson was in the process of migrating the nLab over to the cloud, and he said in [this nForum post](https://nforum.ncatlab.org/discussion/13776/nlab-migration-to-the-cloud/?Focus=97846#Comment_97846) that he was going to make public the new source code for the nLab on github after the migration is over. However, in [this more recent nForum post](https://nforum.ncatlab.org/discussion/13776/nlab-migration-to-the-cloud/?Focus=98028#Comment_98028) Richard Williamson has resigned from the nLab with immediate effect. 

This will cause a significant number of issues for the nLab in the upcoming future. Since Richard Williamson seems to be the only person working on the migration of the nLab to the cloud, with his resignation, it is very likely that nLab would remain in this half-unfinished state in the foreseeable future, where only about 1/20th of the articles in the nLab are editable, and no new articles are capable of be created. Furthermore, the codebase of the nLab here in Github is now outdated and won't ever represent the actual codebase used by the current iteration of the nLab, since the nLab has already switched over to Richard Williamson's new codebase, which is still private.

**Comment by aerskine** [comment]
@madeleine-birchfield thanks for raising the issue! Do you know who has copies of the MySQL database, from various time periods eg pre-migration effort to present day?
