### ISSUE TITLE
Category listing is broken

### ISSUE THREAD

**Issue by adeel** [ncatlab/nlab#4]
http://nforum.mathforge.org/discussion/6207/category-listing-is-broken

Jacques:

> I can't reproduce this bug.
> 
> Adding a space between the ":" and the category name (in this case, "empty") seems to fix the problem on your installation. But that space should not be necessary. And, on MY installation, it has ABSOLUTELY NO EFFECT (as it shouldn't).
> 
> I have no idea why the space makes a difference on your installation.

**Comment by williamsonrichard** [comment]
This is ancient now, so closing.
